### ISSUE TITLE
rime-ice is not shown in the schema list in fcitx5-rime

### ISSUE THREAD

**Issue by 12-G** [xddxdd/nixos-config#3]
Hi, thanks for your nur repos. As shown in title, I can't find the rime-ice in the schema list. Here is my code for fcitx5-rime and default.custom.yaml file.
```nix
{
  pkgs,
  lib,
  config,
  ...
}: {
  i18n.inputMethod = {
    enable = true;
    type = "fcitx5";
    fcitx5.waylandFrontend = true;
    fcitx5.addons = with pkgs; [
      (fcitx5-rime.override {
        rimeDataPkgs =
          [
            pkgs.rime-data
            pkgs.nur.repos.xddxdd.rime-ice
          ];
      })
      fcitx5-chinese-addons
      fcitx5-gtk
    ];
  };

  # Extra variables not covered by Nixos fcitx module
  # Author: Lan tian
  environment.variables = lib.mkIf (!config.i18n.inputMethod.fcitx5.waylandFrontend) {
    INPUT_METHOD = "fcitx";
    SDL_IM_MODULE = "fcitx";
    GLFW_IM_MODULE = "ibus";
    QT_IM_MODULES = "wayland;fcitx;ibus";
  };
}
```
```yaml
patch:
  # 仅使用「雾凇拼音」的默认配置，配置此行即可
  __include: rime_ice_suggestion:/
  # 以下根据自己所需自行定义，仅做参考。
  # 针对对应处方的定制条目，请使用 <recipe>.custom.yaml 中配置，例如 rime_ice.custom.yaml
  __patch:
    menu/page_size: 5
    key_binder/bindings/+:
      # 开启逗号句号翻页
      - { when: paging, accept: comma, send: Page_Up }
      - { when: has_menu, accept: period, send: Page_Down }
```
![image](https://github.com/user-attachments/assets/ff2e5f86-e8b8-49e8-ade5-634bb34673b1)
